src/yajra/Oci8/Schema/Grammars/OracleGrammar.php
src/yajra/Oci8/Schema/OracleBlueprint.php
tests/Oci8SchemaGrammarTest.php

At my company we are using timestampTz and it was missing so I added it.

added timestampTz support

---

src/Oci8/Schema/Comment.php
src/Oci8/Schema/OracleBlueprint.php
src/Oci8/Schema/OracleBuilder.php

When creating a table:
```php
Schema::create('flights', function (Blueprint $table) {
$table->increments('id');
$table->string('name')->comment('Flight name'); /* Column comment */
$table->string('airline')->comment('Airline name'); /* Column comment */
$table->comment = 'Flights table'; /* Table comment */
});
```
When modifying a table:
```php
Schema::table('flights', function ($table) {
$table->comment = 'A flights table'; /* Table comment */
$table->commentColumns = [
'name' => 'This is the flight name', /* Column comment */
'airline' => 'This is the airline name' /* Column comment */
];
});
```

Table and column comments

---

src/Oci8/Query/Processors/OracleProcessor.php

add value check for DateTime instance.

convert datetime instance to string

---

src/Oci8/Oci8Connection.php

removes PDO typehint

---

src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Schema/Grammars/OracleGrammar.php

The prefix schema was missing on the insert, delete, update query.

Fix prefix schema on update, insert, delete query

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

Update the unit tests related to the changes from previous PR

Feat/distilleries 5.2

---

src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBlueprint.php
tests/Oci8SchemaGrammarTest.php

Fixes #162 
While it is working, I'm not sure if the design is good.

add: nvarchar2 support

---

src/Oci8/Schema/Trigger.php

Add wrapper when creating auto-increment trigger that contains reserved words.

Add wrapper when creating auto-increment trigger

---

src/Oci8/Schema/OracleAutoIncrementHelper.php

- Fix fetching of primary key.
- Patch docblocks.

Fix fetching of primary key.

---

src/Oci8/Query/Processors/OracleProcessor.php

This should fix has hasColumn and hasColumns

added processColumnListing

---

src/Oci8/Oci8Connection.php

The current way of executing PL/SQL functions is pretty verbose, so i've created this function to simplify the process.

Function to execute PL/SQL functions at one shoot

---

src/Oci8/Query/Grammars/OracleGrammar.php

This PR will:
* Fix table wrapper that uses as keyword. Fix #211

[5.2] Fix table wrapper that uses as keyword. Fix #211

---

src/Oci8/Query/Grammars/OracleGrammar.php

This PR will:
* Fix table wrapper that uses as keyword. Fix #211

[5.3] Fix table wrapper that uses as keyword. Fix #211

---

src/Oci8/Query/Grammars/OracleGrammar.php

This PR will:
* Fix table wrapper that uses as keyword. Fix #211
* Remove unused import and excess new line.

Fix table wrapper that uses as keyword. Fix #211

---

readme.md
src/Oci8/Auth/OracleUserProvider.php
src/Oci8/Oci8ServiceProvider.php

Same with #216 but for Laravel 5.2.

[5.2] Implement oracle user provider.

---

.gitattributes
.github/ISSUE_TEMPLATE.md

[5.3] Fix git attributes and github template.

---

README.md
composer.json

I have changed composer.json to make it compatible with Laravel 5.4. 
I have tested with Oracle 11g server and everything looks ok.

Add support for Laravel 5.4.

---

composer.json

- Update pdo-via-oci8 version to ^1.3.1.
- Fix #246

Update pdo-via-oci8 version to ^1.3.1

---

src/Oci8/Schema/OracleAutoIncrementHelper.php

Fix error while migrate:rollback:

---

src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/Processors/OracleProcessor.php

[5.4] Patch custom sequence compatibility.

---

.travis.yml
composer.json

this should warn users that their extension is missing! we have a lot of the same issues regarding missing oci8 extension

[5.4] Add oci8 dependency for composer.

---

src/Oci8/Oci8Connection.php

parameter length purpose for custom length in result bindParam

[5.4] Added parameter length in executeFunction

---

src/Oci8/Oci8ServiceProvider.php

Related Issues:
- Fix #279
- https://github.com/laravel/framework/pull/19049
- https://github.com/laravel/framework/issues/19030

[5.4] Upgrade connection resolver for Oracle DB driver registration.

---

README.md

[5.4] Fix typo in README file

---

LICENSE.md
readme.md

This PR will:
- Add extension to license file
- Update license to 2017
- Fix typing error, formatting and broken license link in README

[5.1] Fix license and readme files

---

LICENSE.md
readme.md

This PR will:
- Add extension to license file
- Update license to 2017
- Fix typing error, formatting and broken license link in README
#292

[5.2] Fix license and readme files

---

README.md

[5.3] Fix typo in README file

---

.travis.yml
src/Oci8/Eloquent/OracleEloquent.php
src/Oci8/Query/OracleBuilder.php

- Patch performInsert & Update method.
- Patch update method.
- Fix whereIn, whereNotIn queries when collection was passed.

[5.4] Patch OracleEloquent compatibility

---

src/Oci8/Eloquent/OracleEloquent.php

[5.4] Fix attributes passed. Fix #306.

---

src/Oci8/Eloquent/OracleEloquent.php
src/Oci8/Query/Processors/OracleProcessor.php

Patch docblocks and comments.
Fix #315.

[5.4] Set sequence property as public.

---

src/Oci8/Schema/Grammars/OracleGrammar.php

Add UUID Support by @ChaosPower

[5.4] Add UUID Support

---

src/Oci8/Query/Grammars/OracleGrammar.php
src/config/oracle.php

Tested on my environment. Thank you for watching.

[5.4] Add Oracle 12c ansi pagination support

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

[5.4] Add support for json & jsonb datatype.

---

tests/Oci8SchemaGrammarTest.php

[5.4] Add test for UUID datatype.

---

src/Oci8/Eloquent/OracleEloquent.php
src/Oci8/Oci8Connection.php
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/Processors/OracleProcessor.php

Apply clean code concepts:
- remove unnecessary else statement
- use ternary operator

[5.5] Apply clean code concepts

---

.travis.yml
composer.json
tests/Functional/ProceduresAndFunctionsTest.php

Add composer script to setup docker testing environment.

[5.4] Allow failure on PHP 5.6

---

CHANGELOG.md
composer.json
src/Oci8/Oci8Connection.php
tests/Functional/ProceduresAndFunctionsTest.php

[5.5] Merge changes from 5.4 branch.

---

src/Oci8/Query/Grammars/OracleGrammar.php

avoid wrap() stringify integers, fix #346

[5.5] Do not wrap numeric values. Fix #346.

---

CHANGELOG-5.5.md
CHANGELOG.md

- Applying the recommended date format to the changelog
- Adding links to compare tags
- Adding links to contributors and PRs

[5.5] Formatting changelog files

---

src/Oci8/Oci8Connection.php

This PR is fixing the Reconnect Methods to react to Oracles specific Error Codes
Fixes #364

[5.4] Oracle Error Reconnect Handling

---

CHANGELOG.md

[5.4] Fix docs and PR links

---

src/Oci8/Oci8Connection.php

[5.5] Add Reconnect Logic.

---

src/Oci8/Oci8Connection.php

[5.4] Fix undefined index options.

---

src/Oci8/Query/Processors/OracleProcessor.php

Fix #175 for version 5.1. Please test @mohd-aidi. Thanks!

[5.1] Fix hasColumn function.

---

src/Oci8/Query/Processors/OracleProcessor.php

Fix to handle DateTime Object Binding

---

src/Oci8/Oci8Connection.php

[5.6] Fix Declaration of causedByLostConnection.

---

src/Oci8/Query/OracleBuilder.php
src/Oci8/Schema/OracleAutoIncrementHelper.php

[5.5] Fix php72 Countable compatibility.

---

src/Oci8/Oci8Connection.php

Fix #413, binding issue.

---

src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBuilder.php
tests/Oci8SchemaGrammarTest.php

[5.6] Add support for migrate:fresh command.

---

composer.json

Update to 5.7.

---

README.md

This helps users that need this information

Added service name configuration to readme.md

---

phpunit.xml
src/Oci8/Query/Grammars/OracleGrammar.php
tests/Oci8QueryBuilderTest.php

- Fix #458.
- Add tests for pagination.

[5.7] Fix paginate(1) SQL.

---

README.md
src/Oci8/Oci8Connection.php
src/Oci8/Oci8ServiceProvider.php
src/config/oracle.php

[5.6] Added Support for Oracle Edition Based Redefinition

---

README.md
src/Oci8/Oci8Connection.php
src/Oci8/Oci8ServiceProvider.php
src/config/oracle.php

[5.7] Added Support for Oracle Edition Based Redefinition #439

---

src/Oci8/Query/OracleBuilder.php
src/Oci8/Schema/OracleAutoIncrementHelper.php

[5.4] Fix php72 compatibility.

---

CHANGELOG.md
LICENSE.md

- Fix changelog dates
- Update license to 2019

[5.8] Fix changelog dates & Update license to 2019

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Oci8QueryBuilderTest.php

Add tests for https://github.com/yajra/laravel-oci8/pull/532.

---

src/Oci8/Schema/Sequence.php

Fix doc blocks.

---

src/Oci8/Schema/Grammars/OracleGrammar.php

Fix https://github.com/yajra/laravel-oci8/issues/446.

Add ipAddress and macAddress blueprint.

---

src/Oci8/Schema/Sequence.php
tests/SequenceTest.php

Fix https://github.com/yajra/laravel-oci8/issues/523.

Wrap sequence name with schema prefix if set.

---

src/Oci8/Query/OracleBuilder.php

Add support joinSub method for Oracle (not support "as" for alias)

[6.0] Query Builder method joinSub support Oracle alias.

---

.styleci.yml
LICENSE.md
README.md
composer.json

Add support for Laravel 7.

---

.github/workflows/tests.yml
README.md
composer.json
tests/Oci8QueryBuilderTest.php

Initial support for Laravel 8.

Add initial support for Laravel 8.

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

[8.x] Improve pagination performance.

---

src/Oci8/Oci8Connection.php
tests/Functional/ModelTest.php
tests/Functional/QueryBuilderTest.php
tests/TestCase.php
tests/User.php

[8.x] Fix query builder bulk insert.

---

src/Oci8/Query/OracleBuilder.php

[7.x] Remove table alias in run pagination count query with group.

---

src/Oci8/Query/Grammars/OracleGrammar.php

Fix WhereIn query with more than 2k++ records for Laravel 6.x
Addresses #590 for Laravel 6.x

[6.x] Fix WhereIn query with more than 2k++ records

---

src/Oci8/Connectors/OracleConnector.php

[EDITED]
Hello,
This is to reference my answer in issue #506 regarding non-existent global constants. 
Thanks!

[8.x] Fix non-existent global constants.

---

src/Oci8/Query/Processors/OracleProcessor.php

Fix DB::listen, does not trigger QueryExecuted event on insert.

---

src/Oci8/Connectors/OracleConnector.php

Add default fetch mode

---

.github/workflows/lock-closed-issues.yml

Add lock closed issues workflow

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Database/Oci8SchemaGrammarTest.php

revert: 599, unique function index

---

.github/workflows/tests.yml

chore: add PHP 8.2 test matrix

---

src/Oci8/Schema/OracleAutoIncrementHelper.php

feat: determine max object length based on DB version

---

README.md
src/Oci8/Oci8Connection.php
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleAutoIncrementHelper.php
src/Oci8/Schema/OracleBlueprint.php
src/Oci8/Schema/OracleBuilder.php
src/config/oracle.php
tests/Database/Oci8SchemaGrammarTest.php

feat: change limit character for 12c02

---

src/Oci8/Schema/OracleAutoIncrementHelper.php
tests/Functional/SchemaTest.php

feat: Add comptability with startingValue

---

src/Oci8/Oci8Connection.php

fix: Handle options being passed as part of a binding array

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

as per docs: https://laravel.com/docs/10.x/eloquent#upserts

feat: add support for upsert sql

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Functional/ModelTest.php
tests/MultiBlob.php
tests/TestCase.php

Fix updating models with mutliple nullable blob columns. I added details to the issue #820.
Closes #820

Fix multiple blob update and add test

---

phpunit.xml.dist
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/OracleBuilder.php
tests/Database/Oci8QueryBuilderTest.php

fix: #819
fix: `forPage` SQL
fix: `compileSavepointRollBack`

fix: lock for update implementation

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

fix: lock for update with orders

---

phpunit.xml.dist
src/Oci8/Query/Processors/OracleProcessor.php
src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Functional/ConnectionTest.php
tests/Functional/SchemaTest.php

feat: add support for Schema::getColumns()

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

fix: #843
fix: insertOrIgnore implementation
feat: add support for database cache store

feat: add support for database cache store

---

src/Oci8/Connectors/OracleConnector.php
tests/Database/Oci8ConnectorTest.php

fix: retry on lost connection

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Database/Oci8SchemaGrammarTest.php

fix: Schema::dropIfExists

---

src/Oci8/Connectors/OracleConnector.php
src/Oci8/Query/Processors/OracleProcessor.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBlueprint.php
src/Oci8/Schema/OracleBuilder.php
tests/Database/Oci8ConnectorTest.php
tests/Database/Oci8SchemaGrammarTest.php
tests/Functional/SchemaTest.php

- https://github.com/yajra/laravel-oci8/pull/856
- https://github.com/yajra/laravel-oci8/pull/854
- https://github.com/yajra/laravel-oci8/pull/850
- https://github.com/yajra/laravel-oci8/pull/849
- https://github.com/yajra/laravel-oci8/pull/846
- https://github.com/yajra/laravel-oci8/pull/842

feat: sync 11.x grammar and builder  to 10.x

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

[9.x] revert: #611

---

composer.json
src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Database/Oci8SchemaGrammarTest.php

fix: Laravel 11.15 compatibility

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Database/Oci8SchemaGrammarTest.php

fix: Added "order by" clause to compileColumnExists

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/DatabaseTestCase.php
tests/Database/Oci8QueryBuilderTest.php
tests/Database/QueryBuilderWhereLikeTest.php

https://github.com/laravel/framework/pull/52147

feat: Add whereLike clause to query builder

---

src/Oci8/Oci8Connection.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleAutoIncrementHelper.php
src/Oci8/Schema/Sequence.php
src/Oci8/Schema/Trigger.php
tests/Database/Oci8SchemaGrammarTest.php
tests/Database/SequenceTest.php
tests/Functional/SequenceTest.php
tests/Functional/TriggerTest.php
tests/TestCase.php

fix: #905
fix: drop if exist when using schema prefix https://github.com/yajra/laravel-oci8/pull/909/commits/498fb94a56e107dcc1cc505f43fa32eb0376952d

fix: ORA-00942, wrong trigger prefix

---

src/Oci8/Schema/Grammars/OracleGrammar.php

```php
$table->dateTimeTz('published_at')->nullable();
```

feat: add support for dateTime with timezone

---

.github/workflows/continuous-integration.yml

ci: test against 8.5
