src/yajra/Oci8/Oci8Connection.php
src/yajra/Oci8/Oci8ServiceProvider.php

To avoid separate queries (which increase each application request execution time), added a setSessionVars param that runs a single query with all the values that should be set for php.

Added better alter session approach.

---

src/yajra/Oci8/Query/Processors/OracleProcessor.php

When run on a 64-bit PHP installation, bindParam must be explicitly typed as INOUT with a length to get the correct integer casting

Fix 64-bit PHP bug with INOUT bindParam call

---

src/Oci8/Schema/Comment.php

Any Oracle reserved words need to be wrapped before running comment statements.
For example, the following code on the User table
```php
$table->string('password', 60)->comment('User password');
```
will now generate
```plsql
comment on column user."password" is 'User password'
```
Without this, migrating a Laravel default application, which creates an User table with a Password column, will fail if the developer add some comment on it.

Wrap reserved words when commenting on table or columns

---

src/Oci8/Schema/OracleBlueprint.php
tests/Oci8SchemaGrammarTest.php

The following key suffixes will now be created when no custom index name is set:
* primary > pk
* foreign > fk
* unique > uk
For example:
```php
Schema::create('some_huge_table_name', function (Blueprint $table) {
$table->increments('id');
});
```
Would generate an index called `some_huge_table_name_id_primary`, which have more than 30 chars, not allowed by Oracle.
Now, it will generate an index called `some_huge_table_name_id_pk`, which have less than 30 chars. This will avoid lots of index renaming on your migration scripts. Not all of them, but much more than now.
Requested in #131

Shorter key names

---

src/Oci8/Schema/OracleBuilder.php

The following code will now drop the associated sequence:
```php
Schema::table('name', function (Blueprint $table) {
$table->drop();
});
```
- Fixes #106

Drop sequence if table is dropped through Blueprint

---

.gitignore
src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

When you want to get the columns name of table with laravel you have to do it like this :
```
\Schema::getColumnListing($this->model->getTable());
```
When we do that you have this error
```
Error Code : 1008
Error Message : ORA-01008: not all variables bound
Position : 0
Statement : select column_name from user_tab_columns where table_name = upper(:p0) and column_name = upper(:p1)
Bindings : []
(SQL: select column_name from user_tab_columns where table_name = upper(?) and column_name = upper(?))
```
This fix solve this error

Fork and solve error oracle when you execute getColumnListing

---

src/Oci8/Oci8ServiceProvider.php

When you want use
```php
DB::connection()->getDriverName() == 'oracle'
```
That return null because $config is not give to Oci8Connection. When you give them you can acces to thoses informations. To be complient with the other engine I need it.

Fix new instance Oci8Connection with config on last parameter.

---

src/Oci8/Oci8Connection.php
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/config/oracle.php

I need to make the schema prefix before the table name :
````sql
SELECT * FROM MySchema.PROFILE WHERE 1;
```
I need to add MySchema. To do this I create  a new method `withSchemaPrefix ` and it called in `withTablePrefix `.
I create a new config to ` 'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),`
Regards,
Maxime

Add oracle prefix schema

---

src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/Processors/OracleProcessor.php

Just add sequence on your model and you're done!
```php
public $sequence = 'custom_seq';
```
Code feels like it still can be improved. But for now this is just something quick.
```php
$producer = new User();
$producer->name = 'Doe, John M.';
$producer->save();
// Get Entity / Model ID
$id = $producer->id
```
Just override $primaryKey and add public $sequence to your eloquent models
```php
protected $primaryKey = 'customid';
public $sequence = 'custom_seq';
public $incrementing = true; // true by default 
```
Credits to @yajra for pointing where to place this.

[Proposal] Auto increment primary key using custom sequence without trigger.

---

src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

Refactor the schema prefix. I put the schema prefix in wrapTable like the Schema/OracleGrammar. 
I removed the unused method override only for the prefix method.
Use `all_tab_cols`/`all_tables` instead of `user_tab_columns`/`user_tables` to allow querying tables that aren’t in the same schema that the currently connected user

Refactor the schema prefix and fix user_tables

---

src/Oci8/Eloquent/OracleEloquent.php
tests/OracleEloquentStub.php
tests/OracleEloquentTest.php

If using  `OracleEloquent` as your model, you won't be able to switch the database driver for different stages (e.g. sqlite for unit-testing).

OracleEloquent switch QueryBuilder implementation depending grammar

---

src/Oci8/Eloquent/OracleEloquent.php
tests/OracleEloquentStub.php
tests/OracleEloquentTest.php

If using  `OracleEloquent` as your model, you won't be able to switch the database driver for different stages (e.g. sqlite for unit-testing).
yajra/laravel-oci8#73
(cherry picked from commit 3b00886)

OracleEloquent switch QueryBuilder implementation depending grammar (5.1)

---

src/Oci8/Oci8Connection.php

It turns out the the produced Doctrine connetion was returning the database name as 'user' parameter, thus confusing Doctrine's SchemaManager when returning a table's columns.

Fix 'user' param when creating a Doctrine connection

---

src/Oci8/Oci8ServiceProvider.php

Sometimes you may not need to set the session variables, for example when none of your queries deal with date or timestamp fields.

Added option for skipping setSessionVars.

---

src/Oci8/Schema/Grammars/OracleGrammar.php

This PR will add support for wrapping of schema changes in transaction as per this framework PR: https://github.com/laravel/framework/pull/15780

[5.3] Add support for wrapping of schema changes in transaction.

---

README.md
src/Oci8/Auth/OracleUserProvider.php
src/Oci8/Oci8ServiceProvider.php

When using oracle, we may encounter a problem on authentication because oracle queries are case sensitive by default. 
By using this oracle user provider, we will now be able to avoid user issues when logging in and doing a forgot password failure because of case sensitive search.
To use, just update `auth.php` config and set the driver to `oracle`
```php
'providers' => [
'users' => [
'driver' => 'oracle',
'model' => App\User::class,
],
]

[5.3] Implement oracle user provider.

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Oci8QueryBuilderTest.php

This PR will:
- Implement wrapping of column name.
- Implement wrapping of schema and table name.
This PR might be a **BREAKING CHANGE** to some users in a sense that this will force the proper use of `DB::raw()` on complex SQLs which was previously allowed by the package.
Example breaking code that used to work before this patch:
``` php
$q = DB::table('users')->select('min(id)')->first();
```
The proper way should be:
``` php
$q = DB::table('users')->select(DB::raw('min(id)'))->first();
```

[BC][Security] Implement escaping of column name.

---

src/Oci8/Oci8ServiceProvider.php

I needed a way to update sessionVars without touching the Service Provider file. My goal was to set : 
```
// in database.php or oracle.php add :
'session'  => [
'NLS_COMP'                =>  'LINGUISTIC',
'NLS_SORT'                =>  'BINARY_CI'
],
```
In order to get comparison and sorting right. But the SessionVars array only lives in the Service Provider and there was no way to extend it globally.

Allow update of sessionVars from config

---

src/Oci8/Eloquent/OracleEloquent.php

Minor change. When updating an OracleEloquent, pass the save options through the save function.

[5.3] When updating OracleEloquent, pass save options through.

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8QueryBuilderTest.php

In relation to #262, reserved words should be forced to use lower case column name.

[5.4] Convert reserved words to lower case.

---

src/Oci8/Oci8Connection.php

Currently `$connection->getDoctrineConnection()` returns a new instance of `DoctrineConnection` on every call. It should instead use a singleton.
A related issue is [here](https://github.com/the-control-group/voyager/pull/1171). That issue is happening because a new instance of `DoctrinePlatform` is created on each call, so any added types will be lost.

Change getDoctrineConnection() to use a singleton

---

src/Oci8/Schema/Comment.php

Add table prefix to column comment.

[5.4] Fix missing table prefix when adding comment.

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Oci8QueryBuilderTest.php

Fixes problems with Oracle reserved words resulting in columns not found because of being lower-cased
When a reserved word is lowercased, it won't match table columns that were not explicitly created with lowercase. Default is to treat them as uppercase if enclosed in double quotes. This would result in the following problem:
Error Code    : 904
Error Message : ORA-00904: "label": invalid identifier
Position      : 67
Statement     : insert into "TABLE" ("label") values (:p0) returning "ID" into :p1
Also fixed a broken unit test for deleting a record by ID, where laravel adds the table name to the where clause.
**As a note, I left the Str:upper there, but I do want to ask you about that. In my opinion I can't justify anything that forces either direction. I'd say it would be better to …

[5.5] Use upper case column name for reserved words.

---

src/Oci8/Oci8Connection.php
tests/Functional/ProceduresAndFunctionsTest.php

This PR adds ability to specifiy parameter binding types like this one:
Fixes https://github.com/yajra/laravel-oci8/issues/337
```
$input  = 20;
$output = 0;
$bindings = [
'p1' => $input,
'p2' => [
'value' => &$output,
'type'  => PDO::PARAM_INT
]
];
$connection->executeProcedure($procedureName, $bindings);
```
see tests for more info.  this is a backwards compatible change!
cheers max

[5.4] Extended configuration for parameter bindings

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

[5.5] Use uppercase for reserved words.

---

src/Oci8/Query/OracleBuilder.php

Fix whereNotIn query clause where `orWhere` query is being generated. Same patch implemented on the latest versions.

[5.2] Fix whereNotIn query clause.

---

src/Oci8/Schema/Trigger.php

in case if the table name was all lower case, wrapping it with double-quotes will cause the query to fail.

Fix for table name wrapper

---

src/Oci8/Schema/OracleBlueprint.php

this way it is less likely to have an index name conflict

[5.6] Better way to shorten the index name.

---

src/Oci8/Schema/Sequence.php
tests/Functional/ProceduresAndFunctionsTest.php

The value of maxlength in oci-bind-by-name maybe -1 or another but not null.
this condition cause ORA 01460 but not in all versione of oci8. (http://php.net/manual/en/function.oci-bind-by-name.php)
please fix this error in method "addBindingsToStatement".
You must set $length = -1 instead of $length = null at line 435.
Thanks.

Fix issue #413 - Binding issue.

---

src/Oci8/Schema/Grammars/OracleGrammar.php

[5.6] Escape ENUM column name to avoid problems with reserved words

---

src/Oci8/Query/OracleBuilder.php

This PR fixes the #485 issue with new method `fromSub` in Query Builder class
Needs to be merged in 5.6+ versions

[5.7] Fix #485 - Preventing ORA-00933 when using fromSub method.

---

src/Oci8/Connectors/OracleConnector.php

This PR works in tandem with my other one (https://github.com/yajra/pdo-via-oci8/pull/61)
It sets the correct username / password in the connection details when using external credentials (this only works if a username '`/`' is used with an empty password)
Note: obviously this is not required to enable wallet support (only the one from `pdo-via-oci8` is), but it will save you having to specify it and possibly having to look through the docs to figure out why things don't work :)

[5.7] Facilitate wallet support.

---

src/Oci8/Query/Grammars/OracleGrammar.php

Fix table alias when using capital `AS` on query.

[5.8] Fix stripping of AS from table name.

---

composer.json
src/Oci8/Connectors/OracleConnector.php

Package throws error Class auth not found when running in Laravel Zero CLI framework which does not include auth component.
Found issue to be missing explicit requirement for illuminate/auth in composer.json, which happens to be loaded by default in full laravel framework

[5.8] Added illuminate/auth as dependency in composer.json

---

.travis.yml
composer.json
src/Oci8/Oci8Connection.php
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/Processors/OracleProcessor.php
tests/Oci8ConnectionTest.php
tests/Oci8ConnectorTest.php
tests/Oci8QueryBuilderTest.php
tests/Oci8SchemaGrammarTest.php
tests/OracleEloquentTest.php
tests/SequenceTest.php

- Add support for Laravel 6.
- Use bindValues from base Connection.
- Fix in relation to https://github.com/yajra/pdo-via-oci8/pull/63.
- Fix #521. 
~~This PR relies on https://github.com/yajra/pdo-via-oci8/pull/66.~~
This PR relies on https://github.com/yajra/pdo-via-oci8/pull/67.

[6.0] Laravel 6 support.

---

src/Oci8/Eloquent/OracleEloquent.php

This will add a direct method to fetch the model's next sequence value.
```php
class User extends OracleEloquent
{
public $incrementing = false;
protected $sequence = 'user_id_seq';
}
$user = new User;
$user->id = User::nextValue();
$user->save();
// fetch next value from another sequence.
$user = new User;
$user->id = User::nextValue('user_seq');
$user->save();
````

[6.0] Allow custom sequence name on model nextValue.

---

src/Oci8/Query/Grammars/OracleGrammar.php

With this commit you can make an eloquent query with a relationship on a table with more than 1000 results. 
Extending the model to OracleEloquent doesn't work because does not contamplate this case.

[6.0] Fix whereInRaw and whereNotInRaw Grammar.

---

src/Oci8/Query/Grammars/OracleGrammar.php

Testing I saw this bug. It puts something like this in the query:
`" or "table"."column" "table"."column" in  "`

Fix bug from pull request #532

---

src/Oci8/Query/OracleBuilder.php

I find a a issue that Laravel `paginate` won't work with Oracle connections because of its naming conventions, and it print the message _`Undefined property: stdClass::$aggregate`_.
The Oracle statement _`SELECT COUNT(1) AS aggregate FROM TABLE`_, for instance, will return a column named **`AGGREGATE`**.
Unless the column name is enclosed within double quotes, such as _`SELECT COUNT(1) AS "aggregate" FROM TABLE`_.
Since the `aggregate` field will be converted to `AGGREGATE` in Oracle connections, I think we should also check whether `AGGREGATE` property exists.
Specifically, this issue would happen if set [`options' => [ PDO::ATTR_CASE => PDO::CASE_NATURAL ]`](https://github.com/yajra/laravel-oci8/issues/105#issuecomment-157610358) or  `options' => [ PDO::ATTR_CASE => PDO::CASE_UPPER ]`. …

Fix pagination aggregate count.

---

src/Oci8/Oci8ServiceProvider.php

- Fix database presence validation issue (unique, exists, etc).
- Removes the dependency on OracleUserProvider.
Ref: http://www.dba-oracle.com/t_case_insensitive_indexes_searches.htm
To enable on lower versions, you can use the following code:
```php
class AppServiceProvider extends ServiceProvider
{
/**
* Bootstrap any application services.
*
* @return void
*/
public function boot()
{
DB::setSessionVars([
'NLS_COMP' => 'LINGUISTIC',
'NLS_SORT' => 'BINARY_CI',
]);
}
}
```

[8.x] Enable oracle case insensitive searches.

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Oci8SchemaGrammarTest.php

A security patch for unique constraint to enforce case insensitive matching:
Example:
Both users will be inserted without throwing a constraint error.
```php
users: email (unique)
User::create(['email' => 'admin@example.com']);
User::create(['email' => 'Admin@example.com']);
```
```php
User::create(['email' => 'admin@example.com']);
User::create(['email' => 'Admin@example.com']);
```
Error Message : ORA-00001: unique constraint (SCHEMA.USERS_EMAIL_UK) violated
This patch only works on projects with fresh migrations. For existing projects, you need to create the unique index manually.

[8.x][Security] Implement case insensitive function-based unique index.

---

src/Oci8/Query/Processors/OracleProcessor.php
tests/Functional/ModelTest.php
tests/Functional/ModelTests.php
tests/UserWithGuardedProperty.php

[8.x] Fix Model::create() with guarded property.

---

composer.json
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Query/OracleBuilder.php
tests/Database/Oci8QueryBuilderTest.php
tests/Functional/ModelTest.php
tests/Functional/QueryBuilderTest.php

- Fix run pagination count query with group. https://github.com/yajra/laravel-oci8/pull/615/commits/a3b678a596a74ceee7d730784b7bd1cb1b1107e7
- 8.x version of #614, Fix #613
- Fix fromSub query with table prefix. https://github.com/yajra/laravel-oci8/pull/615/commits/22c6b68d68ccacf5f11f87e17e4daa41cef8a88f
- Fix from query with table alias. https://github.com/yajra/laravel-oci8/pull/615/commits/f2125f998e2df30ff0f843cd10e932848dd48903
- Fix compileUnionAggregate. https://github.com/yajra/laravel-oci8/pull/615/commits/8ead569c9fa64a215b1650e0e5ee67c7f1b5b291
- Fix cross join sub query. https://github.com/yajra/laravel-oci8/pull/615/commits/244a5cd466bb258ec1b3ace86e185239ef51844e
- All applicable builder tests from framework added.
- Add TODO notes on failing / unsupported features and …

[8.x] Query builder fixes and tests.

---

src/Oci8/Schema/Sequence.php

When connections.options in database/config.php has attribute letter-case
settings like `PDO::ATTR_CASE => PDO::CASE_UPPER`, both of
nextValue/currentValue methods will fail retrieving values.
This is because they always expected lower-cased `id` property from stdClass
generated by `selectOne` method.
This patch will quote "id" in SQL as-statement so ensure returned
stdClass object has lower-cased `id` property.
See also:
https://github.com/yajra/laravel-oci8/issues/105
https://github.com/yajra/laravel-oci8/pull/570

bugfix: Quote column name "id" so as to not affected by PDO::ATTR_CASE

---

src/Oci8/Oci8Connection.php
src/Oci8/PDO/Oci8Driver.php

Fix #641
Fixes error below:
> php artisan ide-helper:models -N
Exception: An exception occurred while executing a query: An exception occurred in the driver: ORA-24415: Missing or null username.

[8.x] Add Oci8Driver for the new DBAL implementation.

---

src/Oci8/Connectors/OracleConnector.php
tests/Database/Oci8ConnectorTest.php

In the `checkMultipleHostDsn()` method, this project uses `SERVICE_NAME = {$config['database']}`, which differs from `setServiceId()`:
```php
protected function setServiceId(array $config)
{
$config['service']   = empty($config['service_name'])
? $service_param = 'SID = ' . $config['database']
: $service_param = 'SERVICE_NAME = ' . $config['service_name'];
return $config;
}
```
To unify user experience and ease confusion over configuration, I propose to modify `checkMultipleHostDsn()` method, making CONNECT_DATA the same by using  `$config['service']`:
```php
$config['tns'] = "(DESCRIPTION = {$address} (LOAD_BALANCE = yes) (FAILOVER = on) (CONNECT_DATA = (SERVER = DEDICATED) ({$config['service']})))";
```

Fixed checkMultipleHostDsn SERVICE_NAME using inconsistent database config bugs.

---

.styleci.yml
composer.json
src/Oci8/PDO/Oci8Driver.php
tests/Functional/SchemaTest.php

Fix https://github.com/yajra/laravel-oci8/issues/710
Fix Schema::getColumnType()
Add test for Schema::getColumnType()

[9.x] Add Oci8Driver getName method

---

src/Oci8/Query/Grammars/OracleGrammar.php

Hi, I made some changes for `delete` statement with `join`. I was getting 
`DELETE table_name FROM table_name JOIN other_table ... WHERE ...;`
I updated the query so the result will be it to be
`DELETE (SELECT * FROM table_name JOIN other_table ... WHERE ...);`
Post::join('term_taxonomies', function($query) {
$query->on('term_taxonomies.id', '=', 'term_relationships.term_taxonomy_id')
->where('term_taxonomies.name', '=', 'post_tag');
})
->where('term_relationships.model', '=', 'Post')
->where('term_relationships.model_id', '=', $model->id)
->whereNotIn('term_relationships.term_taxonomy_id', $taxonomies)
->delete();

Update delete query

---

src/Oci8/Schema/OracleBlueprint.php

When creating a compound/composite index with 6 columns we noticed that the while loop to create the index name was never ending, causing the php artisan migrate command to hang.
By providing for recognition of large numbers of columns in compound indicies we can avoid the while loop completely and return out of the function whilst writing a sane and unique index name.

Allow for a large number of column names in compound indicies

---

src/Oci8/Oci8ServiceProvider.php
src/config/oracle.php

fix `not valid month` error with commented ``NLS_DATE_FORMAT``
```
'sessionVars' => [
'NLS_TIME_FORMAT'         => 'HH24:MI:SS',
//        'NLS_DATE_FORMAT'         => 'YYYY-MM-DD HH24:MI:SS',
'NLS_TIMESTAMP_FORMAT'    => 'YYYY-MM-DD HH24:MI:SS',
'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
'NLS_NUMERIC_CHARACTERS'  => '.,',
]
```

feat: make session variables configurable

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

Overrides `compileRandom` main method to be able to call inRandomOrder on models.

feat: add random order on grammar

---

src/Oci8/Schema/OracleBlueprint.php

Creating an index with a long name (> 30 characters) fails on our Oracle infrastructure with the following message:
```
ORA-00969: missing ON keyword
create unique index TABLENAME1_comp_1672411435.011 on PREFIX_TABLENAME1_XXXX (lower(COL1), lower(COL2), lower(COL3))
```
By replacing the dot (.) in the index name "TABLENAME1_comp_1672411435.011", it works again. It is what this patch does.
**System details**
- Ubuntu 20.04.5 LTS / Windows 10
- Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
- PHP 8.0.26 / PHP 8.1.3
- Laravel Version 9.37
- Laravel-OCI8 Version 9.2.0
**Workaround**
As we spotted that this bug was introduced in the 9.0.4 release (https://github.com/yajra/laravel-oci8/pull/735/files#diff-7f7dccef7d6c61cad0d731ccd68ba192f1709deb333679cf51931b0f0d661e7 …

fix: ORA-00969 when creating indexes

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Database/Oci8SchemaGrammarTest.php

From #749
revert: #599, unique function index
(cherry picked from commit a6ac80689028e0b43868330e25c73356a8f25650)

fix: unique index

---

README.md
src/Oci8/Oci8Connection.php
src/Oci8/Query/Grammars/OracleGrammar.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleAutoIncrementHelper.php
src/Oci8/Schema/OracleBlueprint.php
src/Oci8/Schema/OracleBuilder.php
src/config/oracle.php
tests/Database/Oci8SchemaGrammarTest.php

Cherry-picked from https://github.com/yajra/laravel-oci8/pull/762.
Set `ORA_MAX_NAME_LEN=128` on your `.env` file to the new DB object max length.

feat: change limit character for 12c02 #762

---

src/Oci8/Oci8Connection.php

Laravel was updated to allow new functions like `toRawSql()`, but, for this, the reference for the connection should be set in grammars. This update does this, based on MySQL and other standard drivers.
Reference's Link: 
https://github.com/laravel/framework/blob/3cd9bcb25dbfb4e70c9b96dd5b9c2ce109583217/src/Illuminate/Database/MySqlConnection.php#L46
https://github.com/laravel/framework/blob/3cd9bcb25dbfb4e70c9b96dd5b9c2ce109583217/src/Illuminate/Database/MySqlConnection.php#L72

fix to sqlRawSql

---

src/Oci8/Oci8ServiceProvider.php
tests/Functional/SessionVarsTest.php

Fixes https://github.com/yajra/laravel-oci8/issues/811 and improves handle of default values.

fix: read sessionVars config read from current database connection

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

Fix scenario where empty update fields were provided thus all provided column will be included in the update. Fields used on uniqueBy must be removed from update list.
```php
Policy::upsert($values, $uniqueBy);
```

fix: ORA-38104: Columns referenced in the ON Clause cannot be updated

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Functional/ModelTest.php
tests/MultiBlob.php
tests/TestCase.php

Fix updating models with mutliple nullable blob columns. I added details to the issue https://github.com/yajra/laravel-oci8/issues/820.
Closes https://github.com/yajra/laravel-oci8/issues/820

fix: multiple blob update and add test

---

src/Oci8/Schema/Grammars/OracleGrammar.php
tests/Functional/SchemaTest.php

fix: #837
Note: The `auto_increment` flag is not available on the Oracle definition for the version I am using afaik. A null placeholder is added for auto_increment to fix the missing key error. Use with caution until a better solution is found.

fix: missing auto_increment key

---

src/Oci8/Query/Processors/OracleProcessor.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBuilder.php
tests/Database/Oci8SchemaGrammarTest.php
tests/Functional/SchemaTest.php

Goal:
- Be able to use correctly project `barryvdh/laravel-ide-helper`,  especially command  `php artisan ide-helper:models` with oracle
Improves:
- change compileColumns
- add compileForeignKeys
- add and change tests
- improve getColumns / compileColumns, before it was possible getColumns only on user schema, now it possible retrieve columns from others schemas
Possible break change:
- change compileColumns fields:
- string fields (like column name, column type) to lower case;
- nullable to boolean;
- numeric fields (like length) to int;
- change type value based on precision and scale;
- change length value based on type;

feat: Improve schema grammar

---

src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBlueprint.php
tests/Database/Oci8SchemaGrammarTest.php

fix: index name when column name has space

fix: migration when column name has space

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

[10.x] fix: pagination when sorting by string with same values

---

src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBuilder.php
tests/Database/Oci8SchemaGrammarTest.php

fix: #863
fix: #488
```php
class UsersSeeder extends Seeder
{
/**
* Run the database seeds.
*/
public function run(): void
{
Schema::disableForeignKeyConstraints();
// truncate all tables
Permission::truncate();
Role::truncate();
User::truncate();
// truncate pivot tables
DB::table('role_user')->truncate();
DB::table('permission_role')->truncate();
DB::table('permission_user')->truncate();
Schema::enableForeignKeyConstraints();
}
}
```
```bash
php artisan db:seed UsersSeeder
```

feat: disable/enable foreign keys

---

src/Oci8/Oci8ServiceProvider.php

This is a proposed fix for the error (see below) that I encountered while attempting to use yajra/laravel-oci8 with the Laravel Zero micro-framework.  The solution is to test whether the Laravel AuthServiceProvider class exists before attempting to use it.
```
Illuminate\Contracts\Container\BindingResolutionException
Target class [auth] does not exist.
at vendor/illuminate/container/Container.php:940
936▕
937▕         try {
938▕             $reflector = new ReflectionClass($concrete);
939▕         } catch (ReflectionException $e) {
➜ 940▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
```

[11.x] Test for existence of AuthServiceProvider before trying to use it

---

src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleBuilder.php
tests/Database/Oci8SchemaGrammarTest.php

Hi, 
This pr is for implemente the missing method compileTables from laravel
```php
compileTables
```
i write the following query for get all table from database
```sql
SELECT all_tab_comments.table_name AS "name"
FROM all_tab_comments
JOIN all_tables ON all_tab_comments.table_name = all_tables.table_name
WHERE all_tab_comments.owner = '{owner}'
AND all_tab_comments.table_type IN ('TABLE')
ORDER BY all_tab_comments.table_name;
```

feat: Implement compileTables missing method

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

Hi.
Updated the OracleGrammar to correctly prefix both segments of table names when wrapping them.
This pr resolve #886 and i think resolve #875 too

fix: missing prefix on table alias

---

src/Oci8/Eloquent/OracleEloquent.php
src/Oci8/Schema/Grammars/OracleGrammar.php
src/Oci8/Schema/OracleAutoIncrementHelper.php
src/Oci8/Schema/OracleBlueprint.php
tests/Database/Oci8QueryBuilderTest.php

fix: 🐛 multibyte object name causes error

---

src/Oci8/Schema/Grammars/OracleGrammar.php

Update the `OracleGrammar::compileDropAllTables` method to ignore secondary objects.
PR resolves issue [#896](https://github.com/yajra/laravel-oci8/issues/896).

fix: OracleGrammar::compileDropAllTables method to ignore secondary objects.

---

src/Oci8/Query/OracleBuilder.php

i recently upgraded a working project from Laravel 10 to 12 and started to get `Undefined property: stdClass::$aggregate` with paginations. it turned out that it was fixed in an earlier version of the package but removed in latest version so i am putting back the (old) fix

fix pagination error "Undefined property: stdClass::$aggregate"

---

src/Oci8/Query/Processors/OracleProcessor.php

Instead of get the elapsed time the code fixed was getting only the start time. This PR fixes that.

fix: log query time to be compatible with laravel logging

---

src/Oci8/Schema/Sequence.php

Hi Yajra,
This PR addresses an issue that occurs when a prefix is set in the configuration and an attempt is made to drop a sequence:
```php
'prefix' => env('DB_PREFIX', ''),
```
Inside src/Oci8/Schema/Sequence.php, in the drop function, the `$name` parameter is already prefixed 
by the `dropAutoIncrementObjects` method in src/Oci8/Schema/OracleAutoIncrementHelper.php.
As a result, the line `$name = $this->wrap($name);` causes the sequence name to be double-prefixed, which prevents it from being deleted correctly.
so the  `$name = $this->wrap($name);` couse the sequence to be double prefixed and not deleted
```php
public function drop(string $name): bool
{
$name = $this->wrap($name);
if (! $this->exists($name)) {
return true;
}
```
The steps to reproduce the error are as follows: set a …

Fix: Remove unnecessary wrapping of sequence name in drop method

---

src/Oci8/Schema/Comment.php

Hi yajra,
I investigated the issue and found the cause.
When creating a comment on a reserved word, the `parent::wrapValue($value)` function adds double quotes around `$value`.
This leads to the ORA-00904 error, because with double quotes, the column name must match exactly as it was created.
This fix [[BUG] Migration comment not working, ORA-00904](https://github.com/yajra/laravel-oci8/issues/910)

Fix Migration comment not working, ORA-00904

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

Problem:
- Oracle queries with lock() and orderBy() generated duplicate ORDER BY clauses
- Example: "SELECT * FROM table ORDER BY col FOR UPDATE NOWAIT ORDER BY col"
- Caused SQL syntax errors when using lock without limit
Root Cause:
- Original logic only removed ORDER BY from components when both lock AND limit were present
- Without limit, ORDER BY was included in components AND manually appended in lock section
- This resulted in "ORDER BY ... FOR UPDATE NOWAIT ORDER BY ..." pattern

Fix duplicate ORDER BY in Oracle lock queries

---

src/Oci8/Query/Grammars/OracleGrammar.php
tests/Database/Oci8QueryBuilderTest.php

This is a backport of the fix introduced in [#930.](https://github.com/yajra/laravel-oci8/pull/930)
The change ensures the query does not contain multiple ORDER BY clauses and includes tests to cover this case.

Fix duplicate ORDER BY clauses when using lock() without limit() (for 11.x)

---

.github/workflows/semantic-release.yml
.releaserc.yml

This pull request updates the CI/CD workflow to allow Semantic Release to be triggered manually using workflow_dispatch.

CI/CD: Update Semantic Release as manual run
